spring:
  application:
    name: gomp
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:SDLSDFGGUVVU9457VHVNCNVVPS0239CC7}
  access-token-expiration-minutes: 120

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
